/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.UUID;
import org.openapitools.client.model.ArticleType;
import org.openapitools.client.model.ArticleTypeDetails;
import org.openapitools.client.model.Author;
import org.openapitools.client.model.ImageInfo;
import org.openapitools.client.model.Paper;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ArticleStub {
  
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("articleTitle")
  private String articleTitle = null;
  @SerializedName("authors")
  private List<Author> authors = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("preamble")
  private String preamble = null;
  @SerializedName("mainImage")
  private ImageInfo mainImage = null;
  @SerializedName("listImage")
  private ImageInfo listImage = null;
  @SerializedName("premium")
  private Boolean premium = null;
  @SerializedName("publishingTime")
  private String publishingTime = null;
  @SerializedName("updateTime")
  private String updateTime = null;
  @SerializedName("relatedArticles")
  private List<ArticleStub> relatedArticles = null;
  @SerializedName("articleType")
  private ArticleType articleType = null;
  @SerializedName("articleTypeDetails")
  private ArticleTypeDetails articleTypeDetails = null;
  @SerializedName("paper")
  private Paper paper = null;
  @SerializedName("shareUrl")
  private String shareUrl = null;
  @SerializedName("liveReporting")
  private Boolean liveReporting = null;
  @SerializedName("articlePriority")
  private Integer articlePriority = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getArticleTitle() {
    return articleTitle;
  }
  public void setArticleTitle(String articleTitle) {
    this.articleTitle = articleTitle;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Author> getAuthors() {
    return authors;
  }
  public void setAuthors(List<Author> authors) {
    this.authors = authors;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPreamble() {
    return preamble;
  }
  public void setPreamble(String preamble) {
    this.preamble = preamble;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getMainImage() {
    return mainImage;
  }
  public void setMainImage(ImageInfo mainImage) {
    this.mainImage = mainImage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getListImage() {
    return listImage;
  }
  public void setListImage(ImageInfo listImage) {
    this.listImage = listImage;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getPremium() {
    return premium;
  }
  public void setPremium(Boolean premium) {
    this.premium = premium;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPublishingTime() {
    return publishingTime;
  }
  public void setPublishingTime(String publishingTime) {
    this.publishingTime = publishingTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUpdateTime() {
    return updateTime;
  }
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ArticleStub> getRelatedArticles() {
    return relatedArticles;
  }
  public void setRelatedArticles(List<ArticleStub> relatedArticles) {
    this.relatedArticles = relatedArticles;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ArticleType getArticleType() {
    return articleType;
  }
  public void setArticleType(ArticleType articleType) {
    this.articleType = articleType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ArticleTypeDetails getArticleTypeDetails() {
    return articleTypeDetails;
  }
  public void setArticleTypeDetails(ArticleTypeDetails articleTypeDetails) {
    this.articleTypeDetails = articleTypeDetails;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Paper getPaper() {
    return paper;
  }
  public void setPaper(Paper paper) {
    this.paper = paper;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShareUrl() {
    return shareUrl;
  }
  public void setShareUrl(String shareUrl) {
    this.shareUrl = shareUrl;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getLiveReporting() {
    return liveReporting;
  }
  public void setLiveReporting(Boolean liveReporting) {
    this.liveReporting = liveReporting;
  }

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(value = "")
  public Integer getArticlePriority() {
    return articlePriority;
  }
  public void setArticlePriority(Integer articlePriority) {
    this.articlePriority = articlePriority;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticleStub articleStub = (ArticleStub) o;
    return (this.uuid == null ? articleStub.uuid == null : this.uuid.equals(articleStub.uuid)) &&
        (this.title == null ? articleStub.title == null : this.title.equals(articleStub.title)) &&
        (this.articleTitle == null ? articleStub.articleTitle == null : this.articleTitle.equals(articleStub.articleTitle)) &&
        (this.authors == null ? articleStub.authors == null : this.authors.equals(articleStub.authors)) &&
        (this.tags == null ? articleStub.tags == null : this.tags.equals(articleStub.tags)) &&
        (this.preamble == null ? articleStub.preamble == null : this.preamble.equals(articleStub.preamble)) &&
        (this.mainImage == null ? articleStub.mainImage == null : this.mainImage.equals(articleStub.mainImage)) &&
        (this.listImage == null ? articleStub.listImage == null : this.listImage.equals(articleStub.listImage)) &&
        (this.premium == null ? articleStub.premium == null : this.premium.equals(articleStub.premium)) &&
        (this.publishingTime == null ? articleStub.publishingTime == null : this.publishingTime.equals(articleStub.publishingTime)) &&
        (this.updateTime == null ? articleStub.updateTime == null : this.updateTime.equals(articleStub.updateTime)) &&
        (this.relatedArticles == null ? articleStub.relatedArticles == null : this.relatedArticles.equals(articleStub.relatedArticles)) &&
        (this.articleType == null ? articleStub.articleType == null : this.articleType.equals(articleStub.articleType)) &&
        (this.articleTypeDetails == null ? articleStub.articleTypeDetails == null : this.articleTypeDetails.equals(articleStub.articleTypeDetails)) &&
        (this.paper == null ? articleStub.paper == null : this.paper.equals(articleStub.paper)) &&
        (this.shareUrl == null ? articleStub.shareUrl == null : this.shareUrl.equals(articleStub.shareUrl)) &&
        (this.liveReporting == null ? articleStub.liveReporting == null : this.liveReporting.equals(articleStub.liveReporting)) &&
        (this.articlePriority == null ? articleStub.articlePriority == null : this.articlePriority.equals(articleStub.articlePriority));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.articleTitle == null ? 0: this.articleTitle.hashCode());
    result = 31 * result + (this.authors == null ? 0: this.authors.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.preamble == null ? 0: this.preamble.hashCode());
    result = 31 * result + (this.mainImage == null ? 0: this.mainImage.hashCode());
    result = 31 * result + (this.listImage == null ? 0: this.listImage.hashCode());
    result = 31 * result + (this.premium == null ? 0: this.premium.hashCode());
    result = 31 * result + (this.publishingTime == null ? 0: this.publishingTime.hashCode());
    result = 31 * result + (this.updateTime == null ? 0: this.updateTime.hashCode());
    result = 31 * result + (this.relatedArticles == null ? 0: this.relatedArticles.hashCode());
    result = 31 * result + (this.articleType == null ? 0: this.articleType.hashCode());
    result = 31 * result + (this.articleTypeDetails == null ? 0: this.articleTypeDetails.hashCode());
    result = 31 * result + (this.paper == null ? 0: this.paper.hashCode());
    result = 31 * result + (this.shareUrl == null ? 0: this.shareUrl.hashCode());
    result = 31 * result + (this.liveReporting == null ? 0: this.liveReporting.hashCode());
    result = 31 * result + (this.articlePriority == null ? 0: this.articlePriority.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticleStub {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  articleTitle: ").append(articleTitle).append("\n");
    sb.append("  authors: ").append(authors).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  preamble: ").append(preamble).append("\n");
    sb.append("  mainImage: ").append(mainImage).append("\n");
    sb.append("  listImage: ").append(listImage).append("\n");
    sb.append("  premium: ").append(premium).append("\n");
    sb.append("  publishingTime: ").append(publishingTime).append("\n");
    sb.append("  updateTime: ").append(updateTime).append("\n");
    sb.append("  relatedArticles: ").append(relatedArticles).append("\n");
    sb.append("  articleType: ").append(articleType).append("\n");
    sb.append("  articleTypeDetails: ").append(articleTypeDetails).append("\n");
    sb.append("  paper: ").append(paper).append("\n");
    sb.append("  shareUrl: ").append(shareUrl).append("\n");
    sb.append("  liveReporting: ").append(liveReporting).append("\n");
    sb.append("  articlePriority: ").append(articlePriority).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
