/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Author {
  
  @SerializedName("authorByline")
  private String authorByline = null;
  @SerializedName("authorImage")
  private String authorImage = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getAuthorByline() {
    return authorByline;
  }
  public void setAuthorByline(String authorByline) {
    this.authorByline = authorByline;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthorImage() {
    return authorImage;
  }
  public void setAuthorImage(String authorImage) {
    this.authorImage = authorImage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Author author = (Author) o;
    return (this.authorByline == null ? author.authorByline == null : this.authorByline.equals(author.authorByline)) &&
        (this.authorImage == null ? author.authorImage == null : this.authorImage.equals(author.authorImage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.authorByline == null ? 0: this.authorByline.hashCode());
    result = 31 * result + (this.authorImage == null ? 0: this.authorImage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Author {\n");
    
    sb.append("  authorByline: ").append(authorByline).append("\n");
    sb.append("  authorImage: ").append(authorImage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
