/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.BlockShortcodeError;
import org.openapitools.client.model.FactInfo;
import org.openapitools.client.model.ImageInfo;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Block {
  
  @SerializedName("paragraph")
  private String paragraph = null;
  @SerializedName("html")
  private String html = null;
  @SerializedName("image")
  private ImageInfo image = null;
  @SerializedName("factBox")
  private FactInfo factBox = null;
  @SerializedName("headline")
  private String headline = null;
  @SerializedName("shortcodeError")
  private BlockShortcodeError shortcodeError = null;
  @SerializedName("embed")
  private List<Object> embed = null;
  @SerializedName("instagramEmbed")
  private String instagramEmbed = null;
  @SerializedName("infogramEmbed")
  private List<Object> infogramEmbed = null;
  @SerializedName("twitterEmbed")
  private String twitterEmbed = null;
  @SerializedName("facebookEmbed")
  private String facebookEmbed = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getParagraph() {
    return paragraph;
  }
  public void setParagraph(String paragraph) {
    this.paragraph = paragraph;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHtml() {
    return html;
  }
  public void setHtml(String html) {
    this.html = html;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getImage() {
    return image;
  }
  public void setImage(ImageInfo image) {
    this.image = image;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public FactInfo getFactBox() {
    return factBox;
  }
  public void setFactBox(FactInfo factBox) {
    this.factBox = factBox;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHeadline() {
    return headline;
  }
  public void setHeadline(String headline) {
    this.headline = headline;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BlockShortcodeError getShortcodeError() {
    return shortcodeError;
  }
  public void setShortcodeError(BlockShortcodeError shortcodeError) {
    this.shortcodeError = shortcodeError;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getEmbed() {
    return embed;
  }
  public void setEmbed(List<Object> embed) {
    this.embed = embed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInstagramEmbed() {
    return instagramEmbed;
  }
  public void setInstagramEmbed(String instagramEmbed) {
    this.instagramEmbed = instagramEmbed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getInfogramEmbed() {
    return infogramEmbed;
  }
  public void setInfogramEmbed(List<Object> infogramEmbed) {
    this.infogramEmbed = infogramEmbed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTwitterEmbed() {
    return twitterEmbed;
  }
  public void setTwitterEmbed(String twitterEmbed) {
    this.twitterEmbed = twitterEmbed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFacebookEmbed() {
    return facebookEmbed;
  }
  public void setFacebookEmbed(String facebookEmbed) {
    this.facebookEmbed = facebookEmbed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block block = (Block) o;
    return (this.paragraph == null ? block.paragraph == null : this.paragraph.equals(block.paragraph)) &&
        (this.html == null ? block.html == null : this.html.equals(block.html)) &&
        (this.image == null ? block.image == null : this.image.equals(block.image)) &&
        (this.factBox == null ? block.factBox == null : this.factBox.equals(block.factBox)) &&
        (this.headline == null ? block.headline == null : this.headline.equals(block.headline)) &&
        (this.shortcodeError == null ? block.shortcodeError == null : this.shortcodeError.equals(block.shortcodeError)) &&
        (this.embed == null ? block.embed == null : this.embed.equals(block.embed)) &&
        (this.instagramEmbed == null ? block.instagramEmbed == null : this.instagramEmbed.equals(block.instagramEmbed)) &&
        (this.infogramEmbed == null ? block.infogramEmbed == null : this.infogramEmbed.equals(block.infogramEmbed)) &&
        (this.twitterEmbed == null ? block.twitterEmbed == null : this.twitterEmbed.equals(block.twitterEmbed)) &&
        (this.facebookEmbed == null ? block.facebookEmbed == null : this.facebookEmbed.equals(block.facebookEmbed));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paragraph == null ? 0: this.paragraph.hashCode());
    result = 31 * result + (this.html == null ? 0: this.html.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.factBox == null ? 0: this.factBox.hashCode());
    result = 31 * result + (this.headline == null ? 0: this.headline.hashCode());
    result = 31 * result + (this.shortcodeError == null ? 0: this.shortcodeError.hashCode());
    result = 31 * result + (this.embed == null ? 0: this.embed.hashCode());
    result = 31 * result + (this.instagramEmbed == null ? 0: this.instagramEmbed.hashCode());
    result = 31 * result + (this.infogramEmbed == null ? 0: this.infogramEmbed.hashCode());
    result = 31 * result + (this.twitterEmbed == null ? 0: this.twitterEmbed.hashCode());
    result = 31 * result + (this.facebookEmbed == null ? 0: this.facebookEmbed.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block {\n");
    
    sb.append("  paragraph: ").append(paragraph).append("\n");
    sb.append("  html: ").append(html).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  factBox: ").append(factBox).append("\n");
    sb.append("  headline: ").append(headline).append("\n");
    sb.append("  shortcodeError: ").append(shortcodeError).append("\n");
    sb.append("  embed: ").append(embed).append("\n");
    sb.append("  instagramEmbed: ").append(instagramEmbed).append("\n");
    sb.append("  infogramEmbed: ").append(infogramEmbed).append("\n");
    sb.append("  twitterEmbed: ").append(twitterEmbed).append("\n");
    sb.append("  facebookEmbed: ").append(facebookEmbed).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
