/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.FactInfo;
import org.openapitools.client.model.ImageInfo;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Block {
  
  @SerializedName("paragraph")
  private String paragraph = null;
  @SerializedName("html")
  private String html = null;
  @SerializedName("image")
  private ImageInfo image = null;
  @SerializedName("factBox")
  private FactInfo factBox = null;
  @SerializedName("headline")
  private String headline = null;
  @SerializedName("footnote")
  private String footnote = null;
  @SerializedName("question")
  private String question = null;
  @SerializedName("quote")
  private String quote = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getParagraph() {
    return paragraph;
  }
  public void setParagraph(String paragraph) {
    this.paragraph = paragraph;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHtml() {
    return html;
  }
  public void setHtml(String html) {
    this.html = html;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getImage() {
    return image;
  }
  public void setImage(ImageInfo image) {
    this.image = image;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public FactInfo getFactBox() {
    return factBox;
  }
  public void setFactBox(FactInfo factBox) {
    this.factBox = factBox;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHeadline() {
    return headline;
  }
  public void setHeadline(String headline) {
    this.headline = headline;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFootnote() {
    return footnote;
  }
  public void setFootnote(String footnote) {
    this.footnote = footnote;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQuestion() {
    return question;
  }
  public void setQuestion(String question) {
    this.question = question;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQuote() {
    return quote;
  }
  public void setQuote(String quote) {
    this.quote = quote;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block block = (Block) o;
    return (this.paragraph == null ? block.paragraph == null : this.paragraph.equals(block.paragraph)) &&
        (this.html == null ? block.html == null : this.html.equals(block.html)) &&
        (this.image == null ? block.image == null : this.image.equals(block.image)) &&
        (this.factBox == null ? block.factBox == null : this.factBox.equals(block.factBox)) &&
        (this.headline == null ? block.headline == null : this.headline.equals(block.headline)) &&
        (this.footnote == null ? block.footnote == null : this.footnote.equals(block.footnote)) &&
        (this.question == null ? block.question == null : this.question.equals(block.question)) &&
        (this.quote == null ? block.quote == null : this.quote.equals(block.quote));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paragraph == null ? 0: this.paragraph.hashCode());
    result = 31 * result + (this.html == null ? 0: this.html.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.factBox == null ? 0: this.factBox.hashCode());
    result = 31 * result + (this.headline == null ? 0: this.headline.hashCode());
    result = 31 * result + (this.footnote == null ? 0: this.footnote.hashCode());
    result = 31 * result + (this.question == null ? 0: this.question.hashCode());
    result = 31 * result + (this.quote == null ? 0: this.quote.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block {\n");
    
    sb.append("  paragraph: ").append(paragraph).append("\n");
    sb.append("  html: ").append(html).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  factBox: ").append(factBox).append("\n");
    sb.append("  headline: ").append(headline).append("\n");
    sb.append("  footnote: ").append(footnote).append("\n");
    sb.append("  question: ").append(question).append("\n");
    sb.append("  quote: ").append(quote).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
