/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.BoxType;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BoxInfo {
  
  @SerializedName("title")
  private String title = null;
  @SerializedName("headline")
  private String headline = null;
  @SerializedName("content")
  private List<String> content = null;
  @SerializedName("type")
  private BoxType type = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHeadline() {
    return headline;
  }
  public void setHeadline(String headline) {
    this.headline = headline;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getContent() {
    return content;
  }
  public void setContent(List<String> content) {
    this.content = content;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BoxType getType() {
    return type;
  }
  public void setType(BoxType type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoxInfo boxInfo = (BoxInfo) o;
    return (this.title == null ? boxInfo.title == null : this.title.equals(boxInfo.title)) &&
        (this.headline == null ? boxInfo.headline == null : this.headline.equals(boxInfo.headline)) &&
        (this.content == null ? boxInfo.content == null : this.content.equals(boxInfo.content)) &&
        (this.type == null ? boxInfo.type == null : this.type.equals(boxInfo.type));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.headline == null ? 0: this.headline.hashCode());
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoxInfo {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  headline: ").append(headline).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
