/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Category;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CategoryHierarchy {
  
  @SerializedName("name")
  private Category name = null;
  @SerializedName("subcategories")
  private List<Category> subcategories = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Category getName() {
    return name;
  }
  public void setName(Category name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Category> getSubcategories() {
    return subcategories;
  }
  public void setSubcategories(List<Category> subcategories) {
    this.subcategories = subcategories;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryHierarchy categoryHierarchy = (CategoryHierarchy) o;
    return (this.name == null ? categoryHierarchy.name == null : this.name.equals(categoryHierarchy.name)) &&
        (this.subcategories == null ? categoryHierarchy.subcategories == null : this.subcategories.equals(categoryHierarchy.subcategories));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.subcategories == null ? 0: this.subcategories.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryHierarchy {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  subcategories: ").append(subcategories).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
