/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FactInfo {
  
  @SerializedName("factTitle")
  private String factTitle = null;
  @SerializedName("factContent")
  private List<String> factContent = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getFactTitle() {
    return factTitle;
  }
  public void setFactTitle(String factTitle) {
    this.factTitle = factTitle;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getFactContent() {
    return factContent;
  }
  public void setFactContent(List<String> factContent) {
    this.factContent = factContent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactInfo factInfo = (FactInfo) o;
    return (this.factTitle == null ? factInfo.factTitle == null : this.factTitle.equals(factInfo.factTitle)) &&
        (this.factContent == null ? factInfo.factContent == null : this.factContent.equals(factInfo.factContent));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.factTitle == null ? 0: this.factTitle.hashCode());
    result = 31 * result + (this.factContent == null ? 0: this.factContent.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactInfo {\n");
    
    sb.append("  factTitle: ").append(factTitle).append("\n");
    sb.append("  factContent: ").append(factContent).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
