/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Alignment;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ImageInfo {
  
  @SerializedName("url")
  private String url = null;
  @SerializedName("thumb")
  private String thumb = null;
  @SerializedName("caption")
  private String caption = null;
  @SerializedName("alignment")
  private Alignment alignment = null;
  @SerializedName("byline")
  private String byline = null;
  @SerializedName("classes")
  private List<String> classes = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getThumb() {
    return thumb;
  }
  public void setThumb(String thumb) {
    this.thumb = thumb;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCaption() {
    return caption;
  }
  public void setCaption(String caption) {
    this.caption = caption;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Alignment getAlignment() {
    return alignment;
  }
  public void setAlignment(Alignment alignment) {
    this.alignment = alignment;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getByline() {
    return byline;
  }
  public void setByline(String byline) {
    this.byline = byline;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getClasses() {
    return classes;
  }
  public void setClasses(List<String> classes) {
    this.classes = classes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageInfo imageInfo = (ImageInfo) o;
    return (this.url == null ? imageInfo.url == null : this.url.equals(imageInfo.url)) &&
        (this.thumb == null ? imageInfo.thumb == null : this.thumb.equals(imageInfo.thumb)) &&
        (this.caption == null ? imageInfo.caption == null : this.caption.equals(imageInfo.caption)) &&
        (this.alignment == null ? imageInfo.alignment == null : this.alignment.equals(imageInfo.alignment)) &&
        (this.byline == null ? imageInfo.byline == null : this.byline.equals(imageInfo.byline)) &&
        (this.classes == null ? imageInfo.classes == null : this.classes.equals(imageInfo.classes));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.thumb == null ? 0: this.thumb.hashCode());
    result = 31 * result + (this.caption == null ? 0: this.caption.hashCode());
    result = 31 * result + (this.alignment == null ? 0: this.alignment.hashCode());
    result = 31 * result + (this.byline == null ? 0: this.byline.hashCode());
    result = 31 * result + (this.classes == null ? 0: this.classes.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageInfo {\n");
    
    sb.append("  url: ").append(url).append("\n");
    sb.append("  thumb: ").append(thumb).append("\n");
    sb.append("  caption: ").append(caption).append("\n");
    sb.append("  alignment: ").append(alignment).append("\n");
    sb.append("  byline: ").append(byline).append("\n");
    sb.append("  classes: ").append(classes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
