/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.UUID;
import org.openapitools.client.model.ArticleType;
import org.openapitools.client.model.Author;
import org.openapitools.client.model.ImageInfo;
import org.openapitools.client.model.RelatedArticle;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListArticle {
  
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("authors")
  private List<Author> authors = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("preamble")
  private String preamble = null;
  @SerializedName("listImage")
  private ImageInfo listImage = null;
  @SerializedName("premium")
  private Boolean premium = null;
  @SerializedName("publishingTime")
  private String publishingTime = null;
  @SerializedName("updateTime")
  private String updateTime = null;
  @SerializedName("relatedArticles")
  private List<RelatedArticle> relatedArticles = null;
  @SerializedName("articleType")
  private ArticleType articleType = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Author> getAuthors() {
    return authors;
  }
  public void setAuthors(List<Author> authors) {
    this.authors = authors;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPreamble() {
    return preamble;
  }
  public void setPreamble(String preamble) {
    this.preamble = preamble;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getListImage() {
    return listImage;
  }
  public void setListImage(ImageInfo listImage) {
    this.listImage = listImage;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getPremium() {
    return premium;
  }
  public void setPremium(Boolean premium) {
    this.premium = premium;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPublishingTime() {
    return publishingTime;
  }
  public void setPublishingTime(String publishingTime) {
    this.publishingTime = publishingTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUpdateTime() {
    return updateTime;
  }
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<RelatedArticle> getRelatedArticles() {
    return relatedArticles;
  }
  public void setRelatedArticles(List<RelatedArticle> relatedArticles) {
    this.relatedArticles = relatedArticles;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ArticleType getArticleType() {
    return articleType;
  }
  public void setArticleType(ArticleType articleType) {
    this.articleType = articleType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListArticle listArticle = (ListArticle) o;
    return (this.uuid == null ? listArticle.uuid == null : this.uuid.equals(listArticle.uuid)) &&
        (this.title == null ? listArticle.title == null : this.title.equals(listArticle.title)) &&
        (this.authors == null ? listArticle.authors == null : this.authors.equals(listArticle.authors)) &&
        (this.tags == null ? listArticle.tags == null : this.tags.equals(listArticle.tags)) &&
        (this.preamble == null ? listArticle.preamble == null : this.preamble.equals(listArticle.preamble)) &&
        (this.listImage == null ? listArticle.listImage == null : this.listImage.equals(listArticle.listImage)) &&
        (this.premium == null ? listArticle.premium == null : this.premium.equals(listArticle.premium)) &&
        (this.publishingTime == null ? listArticle.publishingTime == null : this.publishingTime.equals(listArticle.publishingTime)) &&
        (this.updateTime == null ? listArticle.updateTime == null : this.updateTime.equals(listArticle.updateTime)) &&
        (this.relatedArticles == null ? listArticle.relatedArticles == null : this.relatedArticles.equals(listArticle.relatedArticles)) &&
        (this.articleType == null ? listArticle.articleType == null : this.articleType.equals(listArticle.articleType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.authors == null ? 0: this.authors.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.preamble == null ? 0: this.preamble.hashCode());
    result = 31 * result + (this.listImage == null ? 0: this.listImage.hashCode());
    result = 31 * result + (this.premium == null ? 0: this.premium.hashCode());
    result = 31 * result + (this.publishingTime == null ? 0: this.publishingTime.hashCode());
    result = 31 * result + (this.updateTime == null ? 0: this.updateTime.hashCode());
    result = 31 * result + (this.relatedArticles == null ? 0: this.relatedArticles.hashCode());
    result = 31 * result + (this.articleType == null ? 0: this.articleType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListArticle {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  authors: ").append(authors).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  preamble: ").append(preamble).append("\n");
    sb.append("  listImage: ").append(listImage).append("\n");
    sb.append("  premium: ").append(premium).append("\n");
    sb.append("  publishingTime: ").append(publishingTime).append("\n");
    sb.append("  updateTime: ").append(updateTime).append("\n");
    sb.append("  relatedArticles: ").append(relatedArticles).append("\n");
    sb.append("  articleType: ").append(articleType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
