/**
 * Lettera
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.UUID;
import org.openapitools.client.model.Author;
import org.openapitools.client.model.ImageInfo;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListArticle {
  
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("author")
  private Author author = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("preamble")
  private String preamble = null;
  @SerializedName("mainImage")
  private ImageInfo mainImage = null;
  @SerializedName("premium")
  private Boolean premium = null;
  @SerializedName("publishingTime")
  private String publishingTime = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Author getAuthor() {
    return author;
  }
  public void setAuthor(Author author) {
    this.author = author;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPreamble() {
    return preamble;
  }
  public void setPreamble(String preamble) {
    this.preamble = preamble;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getMainImage() {
    return mainImage;
  }
  public void setMainImage(ImageInfo mainImage) {
    this.mainImage = mainImage;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getPremium() {
    return premium;
  }
  public void setPremium(Boolean premium) {
    this.premium = premium;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPublishingTime() {
    return publishingTime;
  }
  public void setPublishingTime(String publishingTime) {
    this.publishingTime = publishingTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListArticle listArticle = (ListArticle) o;
    return (this.uuid == null ? listArticle.uuid == null : this.uuid.equals(listArticle.uuid)) &&
        (this.title == null ? listArticle.title == null : this.title.equals(listArticle.title)) &&
        (this.author == null ? listArticle.author == null : this.author.equals(listArticle.author)) &&
        (this.tags == null ? listArticle.tags == null : this.tags.equals(listArticle.tags)) &&
        (this.preamble == null ? listArticle.preamble == null : this.preamble.equals(listArticle.preamble)) &&
        (this.mainImage == null ? listArticle.mainImage == null : this.mainImage.equals(listArticle.mainImage)) &&
        (this.premium == null ? listArticle.premium == null : this.premium.equals(listArticle.premium)) &&
        (this.publishingTime == null ? listArticle.publishingTime == null : this.publishingTime.equals(listArticle.publishingTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.author == null ? 0: this.author.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.preamble == null ? 0: this.preamble.hashCode());
    result = 31 * result + (this.mainImage == null ? 0: this.mainImage.hashCode());
    result = 31 * result + (this.premium == null ? 0: this.premium.hashCode());
    result = 31 * result + (this.publishingTime == null ? 0: this.publishingTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListArticle {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  author: ").append(author).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  preamble: ").append(preamble).append("\n");
    sb.append("  mainImage: ").append(mainImage).append("\n");
    sb.append("  premium: ").append(premium).append("\n");
    sb.append("  publishingTime: ").append(publishingTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
