/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.UUID;
import org.openapitools.client.model.EventType;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Notification {
  
  @SerializedName("contentType")
  private String contentType = null;
  @SerializedName("eventid")
  private Integer eventid = null;
  @SerializedName("eventtype")
  private EventType eventtype = null;
  @SerializedName("uuid")
  private UUID uuid = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getContentType() {
    return contentType;
  }
  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(value = "")
  public Integer getEventid() {
    return eventid;
  }
  public void setEventid(Integer eventid) {
    this.eventid = eventid;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public EventType getEventtype() {
    return eventtype;
  }
  public void setEventtype(EventType eventtype) {
    this.eventtype = eventtype;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notification notification = (Notification) o;
    return (this.contentType == null ? notification.contentType == null : this.contentType.equals(notification.contentType)) &&
        (this.eventid == null ? notification.eventid == null : this.eventid.equals(notification.eventid)) &&
        (this.eventtype == null ? notification.eventtype == null : this.eventtype.equals(notification.eventtype)) &&
        (this.uuid == null ? notification.uuid == null : this.uuid.equals(notification.uuid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.contentType == null ? 0: this.contentType.hashCode());
    result = 31 * result + (this.eventid == null ? 0: this.eventid.hashCode());
    result = 31 * result + (this.eventtype == null ? 0: this.eventtype.hashCode());
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notification {\n");
    
    sb.append("  contentType: ").append(contentType).append("\n");
    sb.append("  eventid: ").append(eventid).append("\n");
    sb.append("  eventtype: ").append(eventtype).append("\n");
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
