/**
 * Lettera
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.UUID;
import org.openapitools.client.model.ImageInfo;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RelatedArticle {
  
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("preamble")
  private String preamble = null;
  @SerializedName("listImage")
  private ImageInfo listImage = null;
  @SerializedName("publishingTime")
  private String publishingTime = null;
  @SerializedName("premium")
  private Boolean premium = null;
  @SerializedName("tags")
  private List<String> tags = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPreamble() {
    return preamble;
  }
  public void setPreamble(String preamble) {
    this.preamble = preamble;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ImageInfo getListImage() {
    return listImage;
  }
  public void setListImage(ImageInfo listImage) {
    this.listImage = listImage;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPublishingTime() {
    return publishingTime;
  }
  public void setPublishingTime(String publishingTime) {
    this.publishingTime = publishingTime;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getPremium() {
    return premium;
  }
  public void setPremium(Boolean premium) {
    this.premium = premium;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedArticle relatedArticle = (RelatedArticle) o;
    return (this.uuid == null ? relatedArticle.uuid == null : this.uuid.equals(relatedArticle.uuid)) &&
        (this.title == null ? relatedArticle.title == null : this.title.equals(relatedArticle.title)) &&
        (this.preamble == null ? relatedArticle.preamble == null : this.preamble.equals(relatedArticle.preamble)) &&
        (this.listImage == null ? relatedArticle.listImage == null : this.listImage.equals(relatedArticle.listImage)) &&
        (this.publishingTime == null ? relatedArticle.publishingTime == null : this.publishingTime.equals(relatedArticle.publishingTime)) &&
        (this.premium == null ? relatedArticle.premium == null : this.premium.equals(relatedArticle.premium)) &&
        (this.tags == null ? relatedArticle.tags == null : this.tags.equals(relatedArticle.tags));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.preamble == null ? 0: this.preamble.hashCode());
    result = 31 * result + (this.listImage == null ? 0: this.listImage.hashCode());
    result = 31 * result + (this.publishingTime == null ? 0: this.publishingTime.hashCode());
    result = 31 * result + (this.premium == null ? 0: this.premium.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedArticle {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  preamble: ").append(preamble).append("\n");
    sb.append("  listImage: ").append(listImage).append("\n");
    sb.append("  publishingTime: ").append(publishingTime).append("\n");
    sb.append("  premium: ").append(premium).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
