/**
 * Lettera
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul> 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Scoring {
  
  @SerializedName("cutoffPriority")
  private List<List<Object>> cutoffPriority = null;
  @SerializedName("cutoffTimeOnSite")
  private List<List<Object>> cutoffTimeOnSite = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<List<Object>> getCutoffPriority() {
    return cutoffPriority;
  }
  public void setCutoffPriority(List<List<Object>> cutoffPriority) {
    this.cutoffPriority = cutoffPriority;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<List<Object>> getCutoffTimeOnSite() {
    return cutoffTimeOnSite;
  }
  public void setCutoffTimeOnSite(List<List<Object>> cutoffTimeOnSite) {
    this.cutoffTimeOnSite = cutoffTimeOnSite;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scoring scoring = (Scoring) o;
    return (this.cutoffPriority == null ? scoring.cutoffPriority == null : this.cutoffPriority.equals(scoring.cutoffPriority)) &&
        (this.cutoffTimeOnSite == null ? scoring.cutoffTimeOnSite == null : this.cutoffTimeOnSite.equals(scoring.cutoffTimeOnSite));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cutoffPriority == null ? 0: this.cutoffPriority.hashCode());
    result = 31 * result + (this.cutoffTimeOnSite == null ? 0: this.cutoffTimeOnSite.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scoring {\n");
    
    sb.append("  cutoffPriority: ").append(cutoffPriority).append("\n");
    sb.append("  cutoffTimeOnSite: ").append(cutoffTimeOnSite).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
